name: CICDPipeline

on:
  push:
    branches: [ master ]

jobs:

  continuous-integration:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v2
      
      #Setup Python 3.9
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
        #Install virtualenv for Python
      - name: Python virtualenv install
        run: pip3 install virtualenv
        #Install testing tools
      - name: Python Bandit & pylint & pylint-exit installation
        run: pip3 install bandit && pip3 install pylint && pip3 install pylint-exit
        #Setup virtual environment for python
      - name:  Python setup virtualenv
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
        # Activate Python virtualenv and install dependencies
      - name: Virtual environment activation and install dependencies
        run: python -m venv venv && source venv/bin/activate &&
          pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
        # Activate virtual environment
      - name: Virtualenv install 
        run: . venv/bin/activate
        #Runs Python Bandit for static security testing of code
      - name: Security test
        run: bandit -r ./app/dynamicsalter_master.py 
        #Checks linting of code, uses pylint-exit to return proper exit codes
      - name: Linting test
        run: pylint ./app/dynamicsalter_master.py || pylint-exit $?
        # Zips up dependencies and creates Lambda.zip
      - name: Dependency zip
        run: |
          cd ./venv/lib/python3.9/site-packages
          zip -r9 ../../../../lambda.zip .
        # Add application to lambda.zip
      - name: Add application to zip file
        run: cd ./app && zip -g ../lambda.zip -r .
        #Upload zip as artifact
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: lambda
          path: lambda.zip

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration] #Will not continue unless testing succeeds
    if: github.ref == 'refs/heads/master'
    steps:
        #Installs AWS CLI using env variables from Actions Secrets
      - name: AWS CLI install
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        #Downloads lambda.zip artifact
      - name: Download Lambda.zip
        uses: actions/download-artifact@v2
        with:
          name: lambda
        #Uploads lambda.zip to S3 bucket
      - name: Upload to S3
        run: aws s3 cp lambda.zip s3://fsa-enterpriseassessment-ethanriverpage/lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        #Deploys lambda.zip within the S3 bucket to AWS Lambda
      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name fsa-enterpriseassessment-lambda --s3-bucket fsa-enterpriseassessment-ethanriverpage --s3-key lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
