name: CICDPipeline

on:
  push:
    branches: [ master ]

jobs:

  continuous-integration:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v2
      
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Python virtualenv install
        run: pip3 install virtualenv

      - name:  Python setup virtualenv
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Dependency install
        run: python -m venv venv && source venv/bin/activate &&
          pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Virtualenv install and pytest      
        run: . venv/bin/activate && pytest
      
      # Step 7
      - name: Dependency zip
        run: |
          cd ./venv/lib/python3.9/site-packages
          zip -r9 ../../../../api.zip .
      
      # Step 8
      - name: Add application to zip file
        run: cd ./app && zip -g ../api.zip -r .
      
      # Step 9
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip